### ISSUE TITLE
Chapter 1. Errata for companion example.

### ISSUE THREAD

**Issue by aztextal** [PacktPublishing/Kotlin-Programming-By-Example#3]
Chapter01/CompanionObject1.kt

must be

class Printer {
    companion object {

i.e. without companion object name.

**Comment by shruthis-shetty** [comment]
Hi @aztextal , can you please elaborate more on this issue?

**Comment by aztextal** [comment]
Chapter01/CompanionObject1.kt can't be compiled, because the example is for unnamed singleton (default name is Companion).
There is pull request for this issue, i don't know how link it here.
https://github.com/PacktPublishing/Kotlin-Programming-By-Example/pull/4

**Comment by shruthis-shetty** [comment]
Hi @aztextal, I hope your issue got solved now. Please give an update.
